name: vexp_chembl_imblearn_env
channels:
  - conda-forge
  - defaults
dependencies:
  - imbalanced-learn=0.11
  - pandas=2.1.4
  - numpy=1.26.3
  - psutil
  - python=3.12.1
  - rdkit=2023.09.4
  - scipy=1.11.4
  - joblib
  - jupyter_client
  - jupyter_core
  - jupyter_server
  - jupyterlab
  - jupyterlab_server
  - scikit-learn=1.3.2
